// import 'package:dolapo/models/projectsModel.dart';

// List<ProjectsModel> projects = [
//   // clrs
//   ProjectsModel(
//       0,
//       "CLRS - Case Law Repository System",
//       "Experience the ultimate digital case law repository system, providing seamless access to a vast collection of legal resources",
//       "assets/images/clrs.png",
//       Metas("", "", "", []),
//       true,
//       "https://caselaw.moj.dl.gov.ng/",
//       false,
//       null),
// // stokopedia
//   ProjectsModel(
//     1,
//     "STOCKOPEDIA: A stock investment mobile app",
//     "Stockopedia is a mobile app that helps users to invest smarter and better",
//     "assets/images/stockopedia.png",
//     Metas("2 weeks", "Sole UI/UX Designer", "Research, UI/UX Design", [
//       "assets/prj/stk1.png",
//       "assets/prj/stk2.png",
//       "assets/prj/stk3.png",
//       "assets/prj/stk4.png",
//       "assets/prj/stk5.png",
//       "assets/prj/stk6.png",
//       "assets/prj/stk7.png",
//       "assets/prj/stk8.png",
//       "assets/prj/stk9.png",
//       "assets/prj/stk10.png",
//       "assets/prj/stk11.png",
//       "assets/prj/stk12.png",
//       "assets/prj/stk13.png",
//       "assets/prj/stk14.png",
//       "assets/prj/stk15.png",
//       "assets/prj/stk16.png",
//       "assets/prj/stk17.png",
//       "assets/prj/stk18.png",
//       "assets/prj/stk19.png",
//       "assets/prj/stk20.png",
//       "assets/prj/stk21.png"
//     ]),
//     false,
//     null,
//     false,
//     null,
//   ),

// // healthpal
//   ProjectsModel(
//     2,
//     "Healthpal - Revolutionizing Healthcare Access in Nigeria (Desktop View)",
//     "Healthpal is transforming the way Nigerians access medical care, making it more accessible, convenient, and personalized for everyone.",
//     "assets/images/health.png",
//     Metas("3 weeks", "Sole UI/UX Designer",
//         "Research, UI Design, UX Design, Responsive web design ", [
//       "assets/prj/health1.png",
//       "assets/prj/health2.png",
//       "assets/prj/health3.png",
//       "assets/prj/health4.png",
//       "assets/prj/health5.png",
//       "assets/prj/health6.png",
//       "assets/prj/health7.png",
//       "assets/prj/health8.png",
//       "assets/prj/health9.png",
//       "assets/prj/health10.png",
//       "assets/prj/health11.png",
//       "assets/prj/health12.png",
//       "assets/prj/health13.png",
//       "assets/prj/health14.png",
//       "assets/prj/health15.png",
//       "assets/prj/health16.png",
//       "assets/prj/health17.png",
//       "assets/prj/health18.png",
//       "assets/prj/health19.png"
//     ]),
//     false,
//     null,
//     false,
//     null,
//   ),

//   // healthpal mobile
//   ProjectsModel(
//     3,
//     "Healthpal - Revolutionizing Healthcare Access in Nigeria (Mobile View)",
//     "Healthpal is transforming the way Nigerians access medical care, making it more accessible, convenient, and personalized for everyone.",
//     "assets/images/hpalmobil.png",
//     Metas("3 weeks", "Sole UI/UX Designer",
//         "Research, UI Design, UX Design, Responsive web design ", [
//       "assets/prj/hpal1.png",
//       "assets/prj/hpal2.png",
//       "assets/prj/hpal3.png",
//       "assets/prj/hpal4.png",
//       "assets/prj/hpal5.png",
//       "assets/prj/hpal6.png",
//       "assets/prj/hpal7.png",
//       "assets/prj/hpal8.png",
//       "assets/prj/hpal9.png",
//       "assets/prj/hpal10.png",
//     ]),
//     false,
//     null,
//     false,
//     null,
//   ),

//   // feyoo web
//   ProjectsModel(
//     4,
//     "Fooyee: Designing a Hotel Booking Website for Unforgettable Experiences (Desktop version)",
//     "A hotel booking website that offers a convenient way to book the perfect accommodations ",
//     "assets/images/fooyee.png",
//     Metas("2 weeks", "Sole UI/UX Designer", "Research, UI/UX Design", [
//       "assets/prj/foo1.png",
//       "assets/prj/foo2.png",
//       "assets/prj/foo3.png",
//       "assets/prj/foo4.png",
//       "assets/prj/foo5.png",
//     ]),
//     false,
//     null,
//     false,
//     null,
//   ),

//   // fooyee mobile
//   ProjectsModel(
//     5,
//     "Fooyee: Designing a Hotel Booking Website for Unforgettable Experiences (Mobile version) ",
//     "A hotel booking website that offers a convenient way to book the perfect accommodations ",
//     "assets/images/fooyee2.png",
//     Metas(
//       "2 weeks",
//       "Sole UI/UX Designer",
//       "Research, UI/UX Design",
//       [
//         "assets/prj/foo11.png",
//         "assets/prj/foo12.png",
//         "assets/prj/foo13.png",
//         "assets/prj/foo14.png",
//         "assets/prj/foo15.png",
//       ],
//     ),
//     false,
//     null,
//     false,
//     null,
//   ),

//   // kryptal
//   ProjectsModel(
//     6,
//     "Designing KRYPTAL - A Centralized Cryptocurrency Trading Platform",
//     "A secured and transparent web3 centralized cryptocurrency trading platform that leverages blockchain technology for seamless trading",
//     "assets/images/kryptal.png",
//     Metas("2 weeks", "Sole UI/UX Designer", "Research, UI/UX Design", [
//       "assets/prj/ky1.png",
//       "assets/prj/ky2.png",
//       "assets/prj/ky3.png",
//     ]),
//     false,
//     null,
//     true,
//     "https://www.behance.net/gallery/153877161/Centralized-trading-platform",
//   ),

//   // maiz
//   ProjectsModel(
//     7,
//     "MIEZ Beauty Lounge and Spa Saloon - UI/UX Case Study",
//     "Discover the ultimate oasis of relaxation and rejuvenation at MIEZ Spa and Beauty Salon.",
//     "assets/images/miez.png",
//     Metas("4 weeks", "UI/UX Designer", "Research, UI/UX Design", [
//       "assets/prj/mz1.png",
//       "assets/prj/mz2.png",
//       "assets/prj/mz3.png",
//       "assets/prj/mz4.png",
//       "assets/prj/mz5.png",
//       "assets/prj/mz6.png",
//       "assets/prj/mz7.png",
//       "assets/prj/mz8.png",
//     ]),
//     false,
//     null,
//     false,
//     null,
//   ),
// ];
